### PR TITLE
Clean up some of the code

### PR DESCRIPTION
**Pull request by mybearworld**
The code currently:
- Modifies the `user` object returned by scratchattach, which is not great code style
- Repeats itself in some places

This PR fixes this.

### CODE REVIEW

**Comment by mybearworld** [comment]
Please do add a license for Pyratch before merging this.

**Comment by GenericProgrammer1234** [comment]
This will absolutely break and require major rewriting for Pyratch Developer Build 3. I am not sure I can do all of that after all of the work I have done today.

**Comment by mybearworld** [comment]
> This will absolutely break and require major rewriting for Pyratch Developer Build 3. I am not sure I can do all of that after all of the work I have done today.

What does it break? It seems to work the same as before for me

**Comment by GenericProgrammer1234** [comment]
I am not completely sure though I don't know how to test it since my code right now on my local machine and this pull request's code seem very incompatible.

**Comment by mybearworld** [comment]
> I am not completely sure though I don't know how to test it since my code right now on my local machine and this pull request's code seem very incompatible.

The PR is based on the Developer Build 3 as of https://github.com/GenericProgrammer1234/Pyratch/commit/f608de46abef8a686eecc8ad9e8e3db419fbb25b. It moves some data from the user object itself to a separate dictionary, no actual functionality change.

**Comment by GenericProgrammer1234** [comment]
(How do you quote?) Oh looking at my checklist I haven't done any changes to the user pages so it should be able to be merged into my code right now. Okay I am going to commit my code.

**Comment by mybearworld** [comment]
> (How do you quote?)

Use the three buttons on the top right of a comment, or copy and paste the comment content in its own line and put `>` before it.




> Oh looking at my checklist I haven't done any changes to the user pages so it should be able to be merged into my code right now. Okay I am going to commit my code.

Great!

**Comment by mybearworld** [comment]
I do change one thing about projects, but that's easily fixed.

**Comment by mybearworld** [comment]
Alright, this is resolved.

**Comment by GenericProgrammer1234** [comment]
Do we seriously need to use `scratchattach` inside of `scr`, why?

**Comment by mybearworld** [comment]
> Do we seriously need to use `scratchattach` inside of `scr`, why?

We don't, but it's much less confusing because you can actually see what module it is. Should I change this back?

**Comment by GenericProgrammer1234** [comment]
> > Do we seriously need to use `scratchattach` inside of `scr`, why?

We don't, but it's much less confusing because you can actually see what module it is. Should I change this back?
It is not that confusing because it literally says that we're importing `scratchattach` as `scr` at the start of the file and I am used to it, so tldr yes.

**Comment by mybearworld** [comment]
> It is not that confusing because it literally says that we're importing `scratchattach` as `scr` at the start of the file and I am used to it, so tldr yes.

Yeah, but it seems much more confusing in the code. I suppose it's a Python convention, though, so I'll change it back.

**Comment by GenericProgrammer1234** [comment]
Python developers like to abbreviate everything or maybe that's just me.

**Comment by mybearworld** [comment]
> Python developers like to abbreviate everything or maybe that's just me.

Yeah, I really don't get why. But `import numpy as np` and thing are really common.

**Comment by GenericProgrammer1234** [comment]
Okay this seems good, I'll merge this into this branch now. I have a bit left for Pyratch Developer Build 3 (we could also just move the remaining stuff into Pyratch Developer Build 4)

**Comment by GenericProgrammer1234** [comment]
It's saying it will commit to the base branch but I don't want it to do that yet, I want this pull request to merge with this branch, not the base branch.

**Comment by mybearworld** [comment]
> It's saying it will commit to the base branch but I don't want it to do that yet, I want this pull request to merge with this branch, not the base branch.

`pyratch-developerbuild3` is the base branch for this commit.

**Comment by GenericProgrammer1234** [comment]
Clicked merge!

**Comment by mybearworld** [comment]
> Clicked merge!

Nice!

**Comment by GenericProgrammer1234** [comment]
Okay I have worked a lot today so I am moving the rest of what I planned today to Pyratch Developer Build 4 and I am going to merge this branch with the main branch now.

**Pull request merged**
